### ISSUE TITLE
Failed to prepare multi-release sources for staged compilation

### ISSUE THREAD

**Issue by pratikpparikh** [metlos/multi-release-jar-maven-plugin#6]
Dear Author,

Below is what I am getting, could you point me what would be wrong?  I have added the module-info.java to /src/main/java-mr/9/module-info.java

[ERROR] Failed to execute goal pw.krejci:multi-release-jar-maven-plugin:0.1.5:compile (default-compile) on project tika-core: Failed to prepare multi-release sources for staged compilation. Destination 'C:\Users\prati\git\tika\tika-core\target\sources-9\descriptor\module-info.java' already exists -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal pw.krejci:multi-release-jar-maven-plugin:0.1.5:compile (default-compile) on project tika-core: Failed to prepare multi-release sources for staged compilation.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.executeForkedExecutions(MojoExecutor.java:352)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:197)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to prepare multi-release sources for staged compilation.
	at pw.krejci.mrc.CompileMojo.execute(CompileMojo.java:183)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 25 more
Caused by: org.apache.commons.io.FileExistsException: Destination 'C:\Users\prati\git\tika\tika-core\target\sources-9\descriptor\module-info.java' already exists
	at org.apache.commons.io.FileUtils.moveFile(FileUtils.java:2986)
	at pw.krejci.mrc.CompileMojo.execute(CompileMojo.java:153)
	... 27 more

Regards,

**Comment by metlos** [comment]
Have you solved your issue? What was the problem? I'm sorry for not being responsive, but I'm currently a little bit short on time..

**Comment by pratikpparikh** [comment]
@metlos i did not.  I just gave up on it.

**Comment by metlos** [comment]
I'm reopening the issue, because it seems like a real problem. Could you please provide a little bit more context for when/how this happened? Ideally, do you have some branch of Tika, that I could use to reproduce it (when I find time to do that)?

**Comment by pratikpparikh** [comment]
@metlos I was trying to create a branch of it.  Let me see if I have the code handy that I can upload it, with the current status.  I will update you as soon as I do.

**Comment by posicat** [comment]
I just got the same error on my build when running under jdk-10.0.2_linux-x64 and Java_9.0.4_11 (Linux x64 as well) (it did under Java 8, but of course not multi-module) however under windows on the same JDK 10.0.2 on Windows it builds just fine.

Quick summary of the project building MR-Jars that have a 9 component of just the module-info.java file, the rest of the jar is compiled for Java 8.

Waiting for Jenkins to finish collecting data[ERROR] Failed to execute goal pw.krejci:multi-release-jar-maven-plugin:0.1.5:compile (default-compile) on project project-core: Failed to prepare multi-release sources for staged compilation. Destination '/home/jenkins/slave1/workspace/project-develop-release/project-core/target/sources-9/descriptor/module-info.java' already exists -> [Help 1]

**Comment by posicat** [comment]
More info, under Linux it's using Maven 3.5.3 and on Windows it's 3.3.9.  Is maven starting to gain support for MR-Jars in later versions and that's mucking up the plugin?  I'll try an earlier Maven on the Linux build box and see if that helps.

**Comment by posicat** [comment]
No change running 3.3.9 on the build box.  Same JDK, same Maven.  Windows handles filenames oddly, what's the same file under Windows may not be under Linux, I've run into that a lot.

**Comment by posicat** [comment]
Turned on -X for the compile, it looks like it's re-running the compile due to stale source ... That appears to be coming from the underlying maven processing, not from your code (I couldn't find a reference to that message at least)  If it's already copied over it may need to be ignored on the second pass or the move in CompileMojo.java:153 blows up.  Or throw a try/catch around that line and log but ignore the FileExistsException.

[DEBUG] CompilerReuseStrategy: reuseCreated
[DEBUG] useIncrementalCompilation enabled
[DEBUG] Stale source detected: /home/jenkins/slave1/workspace/project-develop-release/project-core/target/sources-9/descriptor/module-info.java
[INFO] Changes detected - recompiling the module!

**Comment by pratikpparikh** [comment]
@posicat that is similar to my setup.

**Comment by dcfsc** [comment]
We are seeing the same thing on our Centos 7 Jenkins nodes

```
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal pw.krejci:multi-release-jar-maven-plugin:0.1.5:compile (default-compile) on project fsc-commons-core: Failed to prepare multi-release sources for staged compilation. Destination '/home/jenkins/workspace/fsc-commons-develop-release/fsc-commons-core/target/sources-9/descriptor/module-info.java' already exists -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal pw.krejci:multi-release-jar-maven-plugin:0.1.5:compile (default-compile) on project fsc-commons-core: Failed to prepare multi-release sources for staged compilation.
```
If I run in the same workspace from a local terminal, pointing to the same tools, using this script:

```
#! /bin/bash
export MAVEN_HOME=/home/jenkins/tools/hudson.tasks.Maven_MavenInstallation/Maven_3.3.9
export JAVA_HOME=/home/jenkins/tools/hudson.model.JDK/JDK_10/jdk-10.0.2
export PATH=$MAVEN_HOME/bin:$JAVA_HOME/bin:$PATH
```
The build succeeds. It also succeeds on my local Centos 7 dev box.

Could something in the Jenkins system be triggering this behavior?

```
Executing Maven:  -B -f /home/jenkins/workspace/fsc-commons-develop-release/pom.xml -Dmaven.repo.local=/home/jenkins/workspace/fsc-commons-develop-release/.repository -gs /tmp/global-settings6560609839228954588.xml -X -DskipTests clean deploy
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T10:41:47-06:00)
Maven home: /home/jenkins/tools/hudson.tasks.Maven_MavenInstallation/Maven_3.3.9
Java version: 10.0.2, vendor: Oracle Corporation
Java home: /home/jenkins/tools/hudson.model.JDK/JDK_10/jdk-10.0.2
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-862.9.1.el7.x86_64", arch: "amd64", family: "unix"
[INFO] Error stacktraces are turned on.
[DEBUG] Reading global settings from /tmp/global-settings6560609839228954588.xml
[DEBUG] Reading user settings from /home/jenkins/.m2/settings.xml
[DEBUG] Reading global toolchains from /home/jenkins/tools/hudson.tasks.Maven_MavenInstallation/Maven_3.3.9/conf/toolchains.xml
[DEBUG] Reading user toolchains from /home/jenkins/.m2/toolchains.xml
```
My local toolchain files are either missing or all comments. Never used those anyway...

I added this to the command line: `-Dmaven.compiler.useIncrementalCompilation=false`  and can see it in the output. 
```
[DEBUG] properties used {PATH=/usr/local/b....-e -U -DskipTests=true -DskipITs=true 
   - Dmaven.compiler.useIncrementalCompilation=false,.... 
```
However, upon the invocation of the multibuild plugin, I still see 

```
[INFO] --- multi-release-jar-maven-plugin:0.1.5:compile (default-compile) @ fsc-commons-core ---
[DEBUG] Using compiler 'javac'.
[DEBUG] Adding /home/jenkins/workspace/fsc-commons-develop-release/fsc-commons-core/target/generated-sources/annotations to compile source roots:
  /home/jenkins/workspace/fsc-commons-develop-release/fsc-commons-core/src/main/java
[DEBUG] New compile source roots:
  /home/jenkins/workspace/fsc-commons-develop-release/fsc-commons-core/src/main/java
  /home/jenkins/workspace/fsc-commons-develop-release/fsc-commons-core/target/generated-sources/annotations
[DEBUG] CompilerReuseStrategy: reuseCreated
[DEBUG] useIncrementalCompilation enabled
[DEBUG] Stale source detected: /home/jenkins/workspace/fsc-commons-develop-release/fsc-commons-core/src/main/java/com/follett/fsc/commons/string/UnterminatedQuotedStringException.java
```

I will try adding disable to pom.xml
